2024-08-31 13:05:26,515 INFO RPC interface 'supervisor' initialized
2024-08-31 13:05:26,515 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-08-31 13:05:26,515 INFO supervisord started with pid 1
2024-08-31 13:05:27,517 INFO spawned: 'php-fpm' with pid 7
2024-08-31 13:05:27,518 INFO spawned: 'queue-worker_00' with pid 8
2024-08-31 13:05:27,519 INFO spawned: 'queue-worker_01' with pid 9
2024-08-31 13:05:27,519 INFO spawned: 'schedule-worker_00' with pid 10
2024-08-31 13:05:27,526 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738642832 for <Subprocess at 136071738516688 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:27,526 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738732688 for <Subprocess at 136071738516624 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:27,526 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738731280 for <Subprocess at 136071738516240 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:27,527 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-08-31 13:05:27,527 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-08-31 13:05:27,528 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-08-31 13:05:28,533 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-31 13:05:28,534 INFO spawned: 'queue-worker_00' with pid 13
2024-08-31 13:05:28,535 INFO spawned: 'queue-worker_01' with pid 14
2024-08-31 13:05:28,536 INFO spawned: 'schedule-worker_00' with pid 15
2024-08-31 13:05:28,542 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738642832 for <Subprocess at 136071738516688 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:28,542 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738732432 for <Subprocess at 136071738516624 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:28,543 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738733136 for <Subprocess at 136071738516240 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:28,543 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-08-31 13:05:28,544 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-08-31 13:05:28,544 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-08-31 13:05:30,547 INFO spawned: 'queue-worker_00' with pid 16
2024-08-31 13:05:30,548 INFO spawned: 'queue-worker_01' with pid 17
2024-08-31 13:05:30,549 INFO spawned: 'schedule-worker_00' with pid 18
2024-08-31 13:05:30,555 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071755836560 for <Subprocess at 136071738516688 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:30,555 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738642832 for <Subprocess at 136071738516624 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:30,555 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738733136 for <Subprocess at 136071738516240 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:30,556 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-08-31 13:05:30,556 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-08-31 13:05:30,557 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-08-31 13:05:33,560 INFO spawned: 'queue-worker_00' with pid 19
2024-08-31 13:05:33,561 INFO spawned: 'queue-worker_01' with pid 20
2024-08-31 13:05:33,562 INFO spawned: 'schedule-worker_00' with pid 21
2024-08-31 13:05:33,568 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071758360528 for <Subprocess at 136071738516688 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:33,568 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071755836624 for <Subprocess at 136071738516624 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:33,569 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738515792 for <Subprocess at 136071738516240 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:33,569 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-08-31 13:05:33,569 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-08-31 13:05:33,569 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-08-31 13:05:33,570 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-08-31 13:05:33,570 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-08-31 13:05:34,571 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:29:17,561 WARN received SIGQUIT indicating exit request
2024-09-01 02:29:17,561 INFO waiting for php-fpm to die
2024-09-01 02:29:19,566 INFO stopped: php-fpm (exit status 0)
2024-09-01 02:29:39,158 INFO RPC interface 'supervisor' initialized
2024-09-01 02:29:39,159 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-09-01 02:29:39,159 INFO supervisord started with pid 1
2024-09-01 02:29:40,161 INFO spawned: 'php-fpm' with pid 7
2024-09-01 02:29:40,162 INFO spawned: 'queue-worker_00' with pid 8
2024-09-01 02:29:40,162 INFO spawned: 'queue-worker_01' with pid 9
2024-09-01 02:29:40,163 INFO spawned: 'schedule-worker_00' with pid 10
2024-09-01 02:29:40,169 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775372240 for <Subprocess at 129077775246544 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:40,169 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775462288 for <Subprocess at 129077775246480 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:40,170 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775461712 for <Subprocess at 129077775246096 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:40,170 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:29:40,171 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:29:40,171 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:29:41,177 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-01 02:29:41,178 INFO spawned: 'queue-worker_00' with pid 13
2024-09-01 02:29:41,179 INFO spawned: 'queue-worker_01' with pid 14
2024-09-01 02:29:41,180 INFO spawned: 'schedule-worker_00' with pid 15
2024-09-01 02:29:41,187 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077793387536 for <Subprocess at 129077775246480 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:41,187 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077781523792 for <Subprocess at 129077775246544 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:41,189 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:29:41,189 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775176976 for <Subprocess at 129077775246096 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:41,189 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:29:41,191 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:29:43,194 INFO spawned: 'queue-worker_00' with pid 16
2024-09-01 02:29:43,195 INFO spawned: 'queue-worker_01' with pid 17
2024-09-01 02:29:43,195 INFO spawned: 'schedule-worker_00' with pid 18
2024-09-01 02:29:43,201 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077781523792 for <Subprocess at 129077775246544 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:43,201 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775372240 for <Subprocess at 129077775246480 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:43,202 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775463312 for <Subprocess at 129077775246096 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:43,203 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:29:43,203 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:29:43,203 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:29:46,208 INFO spawned: 'queue-worker_00' with pid 19
2024-09-01 02:29:46,209 INFO spawned: 'queue-worker_01' with pid 20
2024-09-01 02:29:46,209 INFO spawned: 'schedule-worker_00' with pid 21
2024-09-01 02:29:46,215 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775245520 for <Subprocess at 129077775246544 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:46,216 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775172304 for <Subprocess at 129077775246480 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:46,216 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775462992 for <Subprocess at 129077775246096 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:46,216 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:29:46,217 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:29:46,217 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:29:46,217 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-09-01 02:29:46,217 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:29:47,219 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:38:34,627 WARN received SIGQUIT indicating exit request
2024-09-01 02:38:34,627 INFO waiting for php-fpm to die
2024-09-01 02:38:36,633 INFO stopped: php-fpm (exit status 0)
2024-09-01 02:39:00,319 INFO RPC interface 'supervisor' initialized
2024-09-01 02:39:00,320 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-09-01 02:39:00,320 INFO supervisord started with pid 1
2024-09-01 02:39:01,322 INFO spawned: 'php-fpm' with pid 7
2024-09-01 02:39:01,323 INFO spawned: 'queue-worker_00' with pid 8
2024-09-01 02:39:01,324 INFO spawned: 'queue-worker_01' with pid 9
2024-09-01 02:39:01,325 INFO spawned: 'schedule-worker_00' with pid 10
2024-09-01 02:39:01,330 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965031184 for <Subprocess at 138951964760080 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:01,331 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965031568 for <Subprocess at 138951964759312 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:01,332 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965030288 for <Subprocess at 138951964759696 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:01,332 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:39:01,332 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:39:01,333 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:39:02,339 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-01 02:39:02,340 INFO spawned: 'queue-worker_00' with pid 13
2024-09-01 02:39:02,341 INFO spawned: 'queue-worker_01' with pid 14
2024-09-01 02:39:02,341 INFO spawned: 'schedule-worker_00' with pid 15
2024-09-01 02:39:02,347 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951964942672 for <Subprocess at 138951964760080 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:02,348 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965031376 for <Subprocess at 138951964759312 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:02,348 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965032272 for <Subprocess at 138951964759696 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:02,349 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:39:02,349 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:39:02,350 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:39:04,353 INFO spawned: 'queue-worker_00' with pid 16
2024-09-01 02:39:04,354 INFO spawned: 'queue-worker_01' with pid 17
2024-09-01 02:39:04,355 INFO spawned: 'schedule-worker_00' with pid 18
2024-09-01 02:39:04,360 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965030736 for <Subprocess at 138951964760080 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:04,361 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965032208 for <Subprocess at 138951964759312 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:04,361 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965028496 for <Subprocess at 138951964759696 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:04,362 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:39:04,362 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:39:04,363 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:39:07,367 INFO spawned: 'queue-worker_00' with pid 19
2024-09-01 02:39:07,368 INFO spawned: 'queue-worker_01' with pid 20
2024-09-01 02:39:07,369 INFO spawned: 'schedule-worker_00' with pid 21
2024-09-01 02:39:07,374 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965032336 for <Subprocess at 138951964760080 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:07,375 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965030736 for <Subprocess at 138951964759312 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:07,375 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965031056 for <Subprocess at 138951964759696 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:07,376 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:39:07,376 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:39:07,376 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:39:07,376 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-09-01 02:39:07,377 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:39:08,377 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:43:29,653 WARN received SIGQUIT indicating exit request
2024-09-01 02:43:29,653 INFO waiting for php-fpm to die
2024-09-01 02:43:31,657 INFO stopped: php-fpm (exit status 0)
2024-09-01 02:43:45,589 INFO RPC interface 'supervisor' initialized
2024-09-01 02:43:45,589 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-09-01 02:43:45,589 INFO supervisord started with pid 1
2024-09-01 02:43:46,591 INFO spawned: 'php-fpm' with pid 7
2024-09-01 02:43:46,592 INFO spawned: 'queue-worker_00' with pid 8
2024-09-01 02:43:46,592 INFO spawned: 'queue-worker_01' with pid 9
2024-09-01 02:43:46,593 INFO spawned: 'schedule-worker_00' with pid 10
2024-09-01 02:43:46,599 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864361789584 for <Subprocess at 123864353593936 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:46,600 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865040 for <Subprocess at 123864353593744 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:46,600 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353863696 for <Subprocess at 123864353593552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:46,600 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:43:46,601 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:43:46,602 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:43:47,608 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-01 02:43:47,609 INFO spawned: 'queue-worker_00' with pid 13
2024-09-01 02:43:47,610 INFO spawned: 'queue-worker_01' with pid 14
2024-09-01 02:43:47,610 INFO spawned: 'schedule-worker_00' with pid 15
2024-09-01 02:43:47,616 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865104 for <Subprocess at 123864353593936 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:47,617 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865616 for <Subprocess at 123864353593744 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:47,617 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865360 for <Subprocess at 123864353593552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:47,618 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:43:47,618 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:43:47,619 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:43:49,622 INFO spawned: 'queue-worker_00' with pid 16
2024-09-01 02:43:49,623 INFO spawned: 'queue-worker_01' with pid 17
2024-09-01 02:43:49,624 INFO spawned: 'schedule-worker_00' with pid 18
2024-09-01 02:43:49,631 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864373051920 for <Subprocess at 123864353593936 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:49,631 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353864144 for <Subprocess at 123864353593552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:49,631 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865104 for <Subprocess at 123864353593744 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:49,633 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:43:49,633 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:43:49,633 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:43:52,636 INFO spawned: 'queue-worker_00' with pid 19
2024-09-01 02:43:52,637 INFO spawned: 'queue-worker_01' with pid 20
2024-09-01 02:43:52,638 INFO spawned: 'schedule-worker_00' with pid 21
2024-09-01 02:43:52,644 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864373051920 for <Subprocess at 123864353593936 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:52,645 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865104 for <Subprocess at 123864353593744 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:52,646 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:43:52,646 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865360 for <Subprocess at 123864353593552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:52,646 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:43:52,646 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:43:52,646 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-09-01 02:43:52,648 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:43:53,649 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 15:07:09,978 INFO RPC interface 'supervisor' initialized
2024-09-01 15:07:09,978 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-09-01 15:07:09,978 INFO supervisord started with pid 1
2024-09-01 15:07:10,980 INFO spawned: 'php-fpm' with pid 7
2024-09-01 15:07:10,982 INFO spawned: 'queue-worker_00' with pid 8
2024-09-01 15:07:10,983 INFO spawned: 'queue-worker_01' with pid 9
2024-09-01 15:07:10,985 INFO spawned: 'schedule-worker_00' with pid 10
2024-09-01 15:07:10,994 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594224179344 for <Subprocess at 128594202155408 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:10,995 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594202426768 for <Subprocess at 128594202155216 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:10,996 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 15:07:10,997 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 15:07:10,999 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594202425232 for <Subprocess at 128594202155024 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:11,003 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 15:07:12,011 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-01 15:07:12,012 INFO spawned: 'queue-worker_00' with pid 13
2024-09-01 15:07:12,013 INFO spawned: 'queue-worker_01' with pid 14
2024-09-01 15:07:12,014 INFO spawned: 'schedule-worker_00' with pid 15
2024-09-01 15:07:12,021 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594202161872 for <Subprocess at 128594202155408 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:12,022 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594202425232 for <Subprocess at 128594202155216 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:12,022 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594202417424 for <Subprocess at 128594202155024 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:12,023 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 15:07:12,024 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 15:07:12,025 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 15:07:14,028 INFO spawned: 'queue-worker_00' with pid 16
2024-09-01 15:07:14,029 INFO spawned: 'queue-worker_01' with pid 17
2024-09-01 15:07:14,030 INFO spawned: 'schedule-worker_00' with pid 18
2024-09-01 15:07:14,037 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594202422480 for <Subprocess at 128594202155408 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:14,038 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594202417424 for <Subprocess at 128594202155216 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:14,039 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594202202832 for <Subprocess at 128594202155024 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:14,039 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 15:07:14,040 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 15:07:14,041 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 15:07:17,045 INFO spawned: 'queue-worker_00' with pid 19
2024-09-01 15:07:17,046 INFO spawned: 'queue-worker_01' with pid 20
2024-09-01 15:07:17,047 INFO spawned: 'schedule-worker_00' with pid 21
2024-09-01 15:07:17,054 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594224179344 for <Subprocess at 128594202155408 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:17,055 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594202422480 for <Subprocess at 128594202155216 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:17,056 CRIT uncaptured python exception, closing channel <POutputDispatcher at 128594202426704 for <Subprocess at 128594202155024 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:07:17,056 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 15:07:17,057 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 15:07:17,057 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 15:07:17,058 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-09-01 15:07:17,058 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 15:07:18,059 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 15:12:51,418 WARN received SIGQUIT indicating exit request
2024-09-01 15:12:51,418 INFO waiting for php-fpm to die
2024-09-01 15:12:53,424 INFO stopped: php-fpm (exit status 0)
2024-09-01 15:14:18,097 INFO RPC interface 'supervisor' initialized
2024-09-01 15:14:18,098 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-09-01 15:14:18,098 INFO supervisord started with pid 1
2024-09-01 15:14:19,101 INFO spawned: 'php-fpm' with pid 7
2024-09-01 15:14:19,103 INFO spawned: 'queue-worker_00' with pid 8
2024-09-01 15:14:19,105 INFO spawned: 'queue-worker_01' with pid 9
2024-09-01 15:14:19,108 INFO spawned: 'schedule-worker_00' with pid 10
2024-09-01 15:14:19,121 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416450512 for <Subprocess at 131141416178384 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:19,122 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416450960 for <Subprocess at 131141416178320 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:19,124 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 15:14:19,124 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416450320 for <Subprocess at 131141416189584 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:19,126 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 15:14:19,127 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 15:14:20,135 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-01 15:14:20,136 INFO spawned: 'queue-worker_00' with pid 13
2024-09-01 15:14:20,137 INFO spawned: 'queue-worker_01' with pid 14
2024-09-01 15:14:20,138 INFO spawned: 'schedule-worker_00' with pid 15
2024-09-01 15:14:20,145 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416181520 for <Subprocess at 131141416178384 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:20,146 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416451152 for <Subprocess at 131141416178320 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:20,147 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416451728 for <Subprocess at 131141416189584 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:20,147 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 15:14:20,148 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 15:14:20,149 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 15:14:22,152 INFO spawned: 'queue-worker_00' with pid 16
2024-09-01 15:14:22,153 INFO spawned: 'queue-worker_01' with pid 17
2024-09-01 15:14:22,154 INFO spawned: 'schedule-worker_00' with pid 18
2024-09-01 15:14:22,161 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416451984 for <Subprocess at 131141416178384 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:22,162 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416451280 for <Subprocess at 131141416178320 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:22,163 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416450896 for <Subprocess at 131141416189584 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:22,164 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 15:14:22,164 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 15:14:22,165 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 15:14:25,169 INFO spawned: 'queue-worker_00' with pid 19
2024-09-01 15:14:25,170 INFO spawned: 'queue-worker_01' with pid 20
2024-09-01 15:14:25,171 INFO spawned: 'schedule-worker_00' with pid 21
2024-09-01 15:14:25,178 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416181520 for <Subprocess at 131141416178384 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:25,179 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416450768 for <Subprocess at 131141416178320 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:25,180 CRIT uncaptured python exception, closing channel <POutputDispatcher at 131141416450384 for <Subprocess at 131141416189584 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 15:14:25,180 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 15:14:25,181 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 15:14:25,181 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 15:14:25,182 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-09-01 15:14:25,182 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 15:14:26,183 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 16:01:47,094 WARN received SIGQUIT indicating exit request
2024-09-01 16:01:47,094 INFO waiting for php-fpm to die
2024-09-01 16:01:49,101 INFO stopped: php-fpm (exit status 0)
2024-09-02 07:19:38,443 INFO RPC interface 'supervisor' initialized
2024-09-02 07:19:38,443 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-09-02 07:19:38,444 INFO supervisord started with pid 1
2024-09-02 07:19:39,446 INFO spawned: 'php-fpm' with pid 7
2024-09-02 07:19:39,448 INFO spawned: 'queue-worker_00' with pid 8
2024-09-02 07:19:39,448 INFO spawned: 'queue-worker_01' with pid 9
2024-09-02 07:19:39,449 INFO spawned: 'schedule-worker_00' with pid 10
2024-09-02 07:19:39,485 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401962326288 for <Subprocess at 130401962065552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:39,486 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401962326480 for <Subprocess at 130401962054352 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:39,486 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401962326928 for <Subprocess at 130401962054288 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:39,489 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-02 07:19:39,489 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-02 07:19:39,489 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-02 07:19:40,507 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-02 07:19:40,508 INFO spawned: 'queue-worker_00' with pid 13
2024-09-02 07:19:40,509 INFO spawned: 'queue-worker_01' with pid 14
2024-09-02 07:19:40,510 INFO spawned: 'schedule-worker_00' with pid 15
2024-09-02 07:19:40,518 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401962326928 for <Subprocess at 130401962054352 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:40,518 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401962326800 for <Subprocess at 130401962054288 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:40,519 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401962327760 for <Subprocess at 130401962065552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:40,520 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-02 07:19:40,520 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-02 07:19:40,521 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-02 07:19:43,359 INFO spawned: 'queue-worker_00' with pid 16
2024-09-02 07:19:43,360 INFO spawned: 'queue-worker_01' with pid 17
2024-09-02 07:19:43,361 INFO spawned: 'schedule-worker_00' with pid 18
2024-09-02 07:19:43,369 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401983691088 for <Subprocess at 130401962054352 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:43,369 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401962326864 for <Subprocess at 130401962054288 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:43,370 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401962327760 for <Subprocess at 130401962065552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:43,370 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-02 07:19:43,371 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-02 07:19:43,372 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-02 07:19:46,376 INFO spawned: 'queue-worker_00' with pid 19
2024-09-02 07:19:46,377 INFO spawned: 'queue-worker_01' with pid 20
2024-09-02 07:19:46,378 INFO spawned: 'schedule-worker_00' with pid 21
2024-09-02 07:19:46,386 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401970736528 for <Subprocess at 130401962054352 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:46,386 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401962057488 for <Subprocess at 130401962054288 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:46,387 CRIT uncaptured python exception, closing channel <POutputDispatcher at 130401962327760 for <Subprocess at 130401962065552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-02 07:19:46,388 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-02 07:19:46,388 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-09-02 07:19:46,388 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-02 07:19:46,389 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-09-02 07:19:46,389 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-02 07:19:47,390 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
