2024-08-31 13:05:26,515 INFO RPC interface 'supervisor' initialized
2024-08-31 13:05:26,515 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-08-31 13:05:26,515 INFO supervisord started with pid 1
2024-08-31 13:05:27,517 INFO spawned: 'php-fpm' with pid 7
2024-08-31 13:05:27,518 INFO spawned: 'queue-worker_00' with pid 8
2024-08-31 13:05:27,519 INFO spawned: 'queue-worker_01' with pid 9
2024-08-31 13:05:27,519 INFO spawned: 'schedule-worker_00' with pid 10
2024-08-31 13:05:27,526 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738642832 for <Subprocess at 136071738516688 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:27,526 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738732688 for <Subprocess at 136071738516624 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:27,526 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738731280 for <Subprocess at 136071738516240 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:27,527 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-08-31 13:05:27,527 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-08-31 13:05:27,528 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-08-31 13:05:28,533 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-31 13:05:28,534 INFO spawned: 'queue-worker_00' with pid 13
2024-08-31 13:05:28,535 INFO spawned: 'queue-worker_01' with pid 14
2024-08-31 13:05:28,536 INFO spawned: 'schedule-worker_00' with pid 15
2024-08-31 13:05:28,542 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738642832 for <Subprocess at 136071738516688 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:28,542 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738732432 for <Subprocess at 136071738516624 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:28,543 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738733136 for <Subprocess at 136071738516240 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:28,543 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-08-31 13:05:28,544 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-08-31 13:05:28,544 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-08-31 13:05:30,547 INFO spawned: 'queue-worker_00' with pid 16
2024-08-31 13:05:30,548 INFO spawned: 'queue-worker_01' with pid 17
2024-08-31 13:05:30,549 INFO spawned: 'schedule-worker_00' with pid 18
2024-08-31 13:05:30,555 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071755836560 for <Subprocess at 136071738516688 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:30,555 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738642832 for <Subprocess at 136071738516624 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:30,555 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738733136 for <Subprocess at 136071738516240 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:30,556 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-08-31 13:05:30,556 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-08-31 13:05:30,557 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-08-31 13:05:33,560 INFO spawned: 'queue-worker_00' with pid 19
2024-08-31 13:05:33,561 INFO spawned: 'queue-worker_01' with pid 20
2024-08-31 13:05:33,562 INFO spawned: 'schedule-worker_00' with pid 21
2024-08-31 13:05:33,568 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071758360528 for <Subprocess at 136071738516688 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:33,568 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071755836624 for <Subprocess at 136071738516624 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:33,569 CRIT uncaptured python exception, closing channel <POutputDispatcher at 136071738515792 for <Subprocess at 136071738516240 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-08-31 13:05:33,569 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-08-31 13:05:33,569 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-08-31 13:05:33,569 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-08-31 13:05:33,570 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-08-31 13:05:33,570 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-08-31 13:05:34,571 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:29:17,561 WARN received SIGQUIT indicating exit request
2024-09-01 02:29:17,561 INFO waiting for php-fpm to die
2024-09-01 02:29:19,566 INFO stopped: php-fpm (exit status 0)
2024-09-01 02:29:39,158 INFO RPC interface 'supervisor' initialized
2024-09-01 02:29:39,159 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-09-01 02:29:39,159 INFO supervisord started with pid 1
2024-09-01 02:29:40,161 INFO spawned: 'php-fpm' with pid 7
2024-09-01 02:29:40,162 INFO spawned: 'queue-worker_00' with pid 8
2024-09-01 02:29:40,162 INFO spawned: 'queue-worker_01' with pid 9
2024-09-01 02:29:40,163 INFO spawned: 'schedule-worker_00' with pid 10
2024-09-01 02:29:40,169 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775372240 for <Subprocess at 129077775246544 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:40,169 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775462288 for <Subprocess at 129077775246480 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:40,170 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775461712 for <Subprocess at 129077775246096 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:40,170 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:29:40,171 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:29:40,171 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:29:41,177 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-01 02:29:41,178 INFO spawned: 'queue-worker_00' with pid 13
2024-09-01 02:29:41,179 INFO spawned: 'queue-worker_01' with pid 14
2024-09-01 02:29:41,180 INFO spawned: 'schedule-worker_00' with pid 15
2024-09-01 02:29:41,187 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077793387536 for <Subprocess at 129077775246480 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:41,187 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077781523792 for <Subprocess at 129077775246544 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:41,189 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:29:41,189 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775176976 for <Subprocess at 129077775246096 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:41,189 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:29:41,191 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:29:43,194 INFO spawned: 'queue-worker_00' with pid 16
2024-09-01 02:29:43,195 INFO spawned: 'queue-worker_01' with pid 17
2024-09-01 02:29:43,195 INFO spawned: 'schedule-worker_00' with pid 18
2024-09-01 02:29:43,201 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077781523792 for <Subprocess at 129077775246544 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:43,201 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775372240 for <Subprocess at 129077775246480 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:43,202 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775463312 for <Subprocess at 129077775246096 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:43,203 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:29:43,203 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:29:43,203 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:29:46,208 INFO spawned: 'queue-worker_00' with pid 19
2024-09-01 02:29:46,209 INFO spawned: 'queue-worker_01' with pid 20
2024-09-01 02:29:46,209 INFO spawned: 'schedule-worker_00' with pid 21
2024-09-01 02:29:46,215 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775245520 for <Subprocess at 129077775246544 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:46,216 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775172304 for <Subprocess at 129077775246480 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:46,216 CRIT uncaptured python exception, closing channel <POutputDispatcher at 129077775462992 for <Subprocess at 129077775246096 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:29:46,216 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:29:46,217 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:29:46,217 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:29:46,217 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-09-01 02:29:46,217 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:29:47,219 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:38:34,627 WARN received SIGQUIT indicating exit request
2024-09-01 02:38:34,627 INFO waiting for php-fpm to die
2024-09-01 02:38:36,633 INFO stopped: php-fpm (exit status 0)
2024-09-01 02:39:00,319 INFO RPC interface 'supervisor' initialized
2024-09-01 02:39:00,320 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-09-01 02:39:00,320 INFO supervisord started with pid 1
2024-09-01 02:39:01,322 INFO spawned: 'php-fpm' with pid 7
2024-09-01 02:39:01,323 INFO spawned: 'queue-worker_00' with pid 8
2024-09-01 02:39:01,324 INFO spawned: 'queue-worker_01' with pid 9
2024-09-01 02:39:01,325 INFO spawned: 'schedule-worker_00' with pid 10
2024-09-01 02:39:01,330 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965031184 for <Subprocess at 138951964760080 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:01,331 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965031568 for <Subprocess at 138951964759312 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:01,332 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965030288 for <Subprocess at 138951964759696 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:01,332 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:39:01,332 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:39:01,333 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:39:02,339 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-01 02:39:02,340 INFO spawned: 'queue-worker_00' with pid 13
2024-09-01 02:39:02,341 INFO spawned: 'queue-worker_01' with pid 14
2024-09-01 02:39:02,341 INFO spawned: 'schedule-worker_00' with pid 15
2024-09-01 02:39:02,347 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951964942672 for <Subprocess at 138951964760080 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:02,348 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965031376 for <Subprocess at 138951964759312 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:02,348 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965032272 for <Subprocess at 138951964759696 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:02,349 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:39:02,349 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:39:02,350 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:39:04,353 INFO spawned: 'queue-worker_00' with pid 16
2024-09-01 02:39:04,354 INFO spawned: 'queue-worker_01' with pid 17
2024-09-01 02:39:04,355 INFO spawned: 'schedule-worker_00' with pid 18
2024-09-01 02:39:04,360 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965030736 for <Subprocess at 138951964760080 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:04,361 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965032208 for <Subprocess at 138951964759312 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:04,361 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965028496 for <Subprocess at 138951964759696 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:04,362 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:39:04,362 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:39:04,363 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:39:07,367 INFO spawned: 'queue-worker_00' with pid 19
2024-09-01 02:39:07,368 INFO spawned: 'queue-worker_01' with pid 20
2024-09-01 02:39:07,369 INFO spawned: 'schedule-worker_00' with pid 21
2024-09-01 02:39:07,374 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965032336 for <Subprocess at 138951964760080 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:07,375 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965030736 for <Subprocess at 138951964759312 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:07,375 CRIT uncaptured python exception, closing channel <POutputDispatcher at 138951965031056 for <Subprocess at 138951964759696 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:39:07,376 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:39:07,376 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:39:07,376 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:39:07,376 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-09-01 02:39:07,377 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:39:08,377 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:43:29,653 WARN received SIGQUIT indicating exit request
2024-09-01 02:43:29,653 INFO waiting for php-fpm to die
2024-09-01 02:43:31,657 INFO stopped: php-fpm (exit status 0)
2024-09-01 02:43:45,589 INFO RPC interface 'supervisor' initialized
2024-09-01 02:43:45,589 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-09-01 02:43:45,589 INFO supervisord started with pid 1
2024-09-01 02:43:46,591 INFO spawned: 'php-fpm' with pid 7
2024-09-01 02:43:46,592 INFO spawned: 'queue-worker_00' with pid 8
2024-09-01 02:43:46,592 INFO spawned: 'queue-worker_01' with pid 9
2024-09-01 02:43:46,593 INFO spawned: 'schedule-worker_00' with pid 10
2024-09-01 02:43:46,599 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864361789584 for <Subprocess at 123864353593936 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:46,600 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865040 for <Subprocess at 123864353593744 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:46,600 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353863696 for <Subprocess at 123864353593552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:46,600 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:43:46,601 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:43:46,602 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:43:47,608 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-01 02:43:47,609 INFO spawned: 'queue-worker_00' with pid 13
2024-09-01 02:43:47,610 INFO spawned: 'queue-worker_01' with pid 14
2024-09-01 02:43:47,610 INFO spawned: 'schedule-worker_00' with pid 15
2024-09-01 02:43:47,616 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865104 for <Subprocess at 123864353593936 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:47,617 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865616 for <Subprocess at 123864353593744 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:47,617 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865360 for <Subprocess at 123864353593552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:47,618 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:43:47,618 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:43:47,619 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:43:49,622 INFO spawned: 'queue-worker_00' with pid 16
2024-09-01 02:43:49,623 INFO spawned: 'queue-worker_01' with pid 17
2024-09-01 02:43:49,624 INFO spawned: 'schedule-worker_00' with pid 18
2024-09-01 02:43:49,631 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864373051920 for <Subprocess at 123864353593936 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:49,631 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353864144 for <Subprocess at 123864353593552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:49,631 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865104 for <Subprocess at 123864353593744 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:49,633 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:43:49,633 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:43:49,633 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:43:52,636 INFO spawned: 'queue-worker_00' with pid 19
2024-09-01 02:43:52,637 INFO spawned: 'queue-worker_01' with pid 20
2024-09-01 02:43:52,638 INFO spawned: 'schedule-worker_00' with pid 21
2024-09-01 02:43:52,644 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864373051920 for <Subprocess at 123864353593936 with name queue-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:52,645 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865104 for <Subprocess at 123864353593744 with name queue-worker_01 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:52,646 WARN exited: queue-worker_00 (exit status 1; not expected)
2024-09-01 02:43:52,646 CRIT uncaptured python exception, closing channel <POutputDispatcher at 123864353865360 for <Subprocess at 123864353593552 with name schedule-worker_00 in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2024-09-01 02:43:52,646 INFO gave up: queue-worker_00 entered FATAL state, too many start retries too quickly
2024-09-01 02:43:52,646 WARN exited: queue-worker_01 (exit status 1; not expected)
2024-09-01 02:43:52,646 INFO gave up: queue-worker_01 entered FATAL state, too many start retries too quickly
2024-09-01 02:43:52,648 WARN exited: schedule-worker_00 (exit status 1; not expected)
2024-09-01 02:43:53,649 INFO gave up: schedule-worker_00 entered FATAL state, too many start retries too quickly
